export enum Cuisine {
  AFRICAN = "African",
  ASIAN = "Asian",
  AMERICAN = "American",
  BRITISH = "British",
  CAJUN = "Cajun",
  CARIBBEAN = "Caribbean",
  CHINESE = "Chinese",
  EASTERN_EUROPEAN = "Eastern European",
  EUROPEAN = "European",
  FRENCH = "French",
  GERMAN = "German",
  GREEK = "Greek",
  INDIAN = "Indian",
  IRISH = "Irish",
  ITALIAN = "Italian",
  JAPANESE = "Japanese",
  JEWISH = "Jewish",
  KOREAN = "Korean",
  LATIN_AMERICAN = "Latin American",
  MEDITERRANEAN = "Mediterranean",
  MEXICAN = "Mexican",
  MIDDLE_EASTERN = "Middle Eastern",
  NORDIC = "Nordic",
  SOUTHERN = "Southern",
  SPANISH = "Spanish",
  THAI = "Thai",
  VIETNAMESE = "Vietnamese",
}

export enum Diet {
  GLUTEN_FREE = "Gluten Free",
  KETOGENIC = "Ketogenic",
  VEGETARIAN = "Vegetarian",
  LACTO_VEGETARIAN = "Lacto-Vegetarian",
  OVO_VEGETARIAN = "Ovo-Vegetarian",
  VEGAN = "Vegan",
  PESCETARIAN = "Pescetarian",
  PALEO = "Paleo",
  PRIMAL = "Primal",
  LOW_FODMAP = "Low FODMAP",
  WHOLE30 = "Whole30",
}

export enum Intolerance {
  DAIRY = "Dairy",
  EGG = "Egg",
  GLUTEN = "Gluten",
  GRAIN = "Grain",
  PEANUT = "Peanut",
  SEAFOOD = "Seafood",
  SESAME = "Sesame",
  SHELLFISH = "Shellfish",
  SOY = "Soy",
  SULFITE = "Sulfite",
  TREE_NUT = "Tree Nut",
  WHEAT = "Wheat",
}

export enum MealType {
  MAIN_COURSE = "Main Course",
  SIDE_DISH = "Side Dish",
  DESSERT = "Dessert",
  APPETIZER = "Appetizer",
  SALAD = "Salad",
  BREAD = "Bread",
  BREAKFAST = "Breakfast",
  SOUP = "Soup",
  BEVERAGE = "Beverage",
  SAUCE = "Sauce",
}

export enum SortingOption {
  META_SCORE = "meta-score",
  POPULARITY = "popularity",
  HEALTHINESS = "healthiness",
  PRICE = "price",
  TIME = "time",
  RANDOM = "random",
  MAX_USED_INGREDIENTS = "max-used-ingredients",
  MIN_MISSING_INGREDIENTS = "min-missing-ingredients",
  ALCOHOL = "alcohol",
  CAFFEINE = "caffeine",
  COPPER = "copper",
  ENERGY = "energy",
  CALORIES = "calories",
  CALCIUM = "calcium",
  CARBOHYDRATES = "carbohydrates",
  CARBS = "carbs",
  CHOLINE = "choline",
  CHOLESTEROL = "cholesterol",
  TOTAL_FAT = "total-fat",
  FLUORIDE = "fluoride",
  TRANS_FAT = "trans-fat",
  SATURATED_FAT = "saturated-fat",
  MONO_UNSATURATED_FAT = "mono-unsaturated-fat",
  POLY_UNSATURATED_FAT = "poly-unsaturated-fat",
  FIBER = "fiber",
  FOLATE = "folate",
  FOLIC_ACID = "folic-acid",
  IODINE = "iodine",
  IRON = "iron",
  MAGNESIUM = "magnesium",
  MANGANESE = "manganese",
  VITAMIN_B3 = "vitamin-b3",
  NIACIN = "niacin",
  VITAMIN_B5 = "pantothenic-acid",
  PHOSPHORUS = "phosphorus",
  POTASSIUM = "potassium",
  PROTEIN = "protein",
  VITAMIN_B2 = "vitamin-b2",
  RIBOFLAVIN = "riboflavin",
  SELENIUM = "selenium",
  SODIUM = "sodium",
  VITAMIN_B1 = "vitamin-b1",
  THIAMIN = "thiamin",
  VITAMIN_A = "vitamin-a",
  VITAMIN_B6 = "vitamin-b6",
  VITAMIN_B12 = "vitamin-b12",
  VITAMIN_C = "vitamin-c",
  VITAMIN_D = "vitamin-d",
  VITAMIN_E = "vitamin-e",
  VITAMIN_K = "vitamin-k",
  SUGAR = "sugar",
  ZINC = "zinc",
}
